services:
  db:
    image: postgres:13
    container_name: occ-odoo17-db-prod
    restart: always
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./odoo
      dockerfile: Dockerfile
    container_name: occ-odoo17-web-prod
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./odoo/addons:/odoo/addons
      - ./filestore:/var/lib/odoo/filestore
      - odoo-config:/etc/odoo
    depends_on:
      - db
    secrets:
      - odoo_admin_password
      - odoo_db_user
      - odoo_db_password
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 30s
      timeout: 10s
      retries: 5

  tomcat:
    build:
      context: ./tomcat
    container_name: occ-tomcat-prod
    ports:
      - "8080:8080"
    volumes:
      - ./odoo/addons:/odoo/addons
    tty: true
    stdin_open: true
    environment:
      - JAVA_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED

secrets:
  odoo_admin_password:
    file: ./secrets/odoo_admin_password
  odoo_db_user:
    file: ./secrets/odoo_db_user
  odoo_db_password:
    file: ./secrets/odoo_db_password
  postgres_password:
    file: ./secrets/postgres_password

volumes:
  db-data:
  odoo-filestore:
  odoo-config: