from . import hr_leave
from . import employee_dependents
from . import employee_incident
from . import employee_position
from . import employee_relationship_line
from . import hr_contract
from . import hr_degree
from . import hr_dependents
from . import hr_employee_base
from . import hr_employee_education
from . import hr_employee_seminar
from . import hr_employee
from . import hr_relationship
from . import hr_schools
from . import hr_work_location
from . import nature_discipline
from . import penalty_sanction
from . import employee_type
from . import employee_type_category
